
FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .


FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    sqlite3 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/sql ./sql
COPY --from=builder /app/uploads ./uploads
COPY --from=builder /app/database ./database
COPY --from=builder /app/conf.json ./

EXPOSE 8080

CMD ["./main"]
