CREATE TABLE IF NOT EXISTS message (
			id TEXT PRIMARY KEY,
			senderID TEXT NOT NULL,
			receiverID TEXT NOT NULL,
			content TEXT NOT NULL,
			createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY (senderID) REFERENCES user(id) ON DELETE CASCADE,
			FOREIGN KEY (receiverID) REFERENCES user(id) ON DELETE CASCADE
		);
