CREATE TABLE IF NOT EXISTS comment (
			id TEXT PRIMARY KEY,
			text TEXT NOT NULL,
			authorID TEXT NOT NULL,
			postID TEXT NOT NULL,
			createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			image TEXT,
			FOREIGN KEY (authorID) REFERENCES user(id) ON DELETE CASCADE,
			FOREIGN KEY (postID) REFERENCES post(id) ON DELETE CASCADE
		);